name: Track LLVM Changes

on:
  schedule:
    # 10:00 AM UTC is 3AM Pacific Time
    - cron: '0 10 * * *'
  pull_request: {}
  workflow_dispatch:

jobs:
  track-llvm-changes:
    name: Track LLVM Changes
    runs-on: ubuntu-20.04
    steps:
      # Clone the CIRCT repo and its submodules. Do shallow clone to save clone
      # time.
      - name: Get CIRCT
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: "true"

      - name: Configure Project
        run: |
          mkdir build
          cd build
          cmake ../llvm/llvm \
            -DBUILD_SHARED_LIBS=ON \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_TARGETS_TO_BUILD=host \
            -DLLVM_BUILD_EXAMPLES=OFF \
            -DLLVM_INSTALL_UTILS=OFF \
            -DLLVM_ENABLE_OCAMLDOC=OFF \
            -DLLVM_ENABLE_BINDINGS=OFF \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_EXTERNAL_PROJECTS=circt \
            -DLLVM_EXTERNAL_CIRCT_SOURCE_DIR=$PWD/..

      - name: Build current LLVM commit
        id: build-current-llvm-commit
        run: |
          cd llvm
          cmake --build ../build --config Debug --target check-circt --
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      
      - name: Build latest LLVM commit
        id: build-latest-llvm-commit
        continue-on-error: true
        run: |
          cd llvm
          git fetch origin main
          git checkout --detach origin/main
          cmake --build ../build --config Debug --target check-circt --
          echo "::set-output name=sha::$(git rev-parse HEAD)"
      
      - name: Bisect commits
        if: steps.build-latest-llvm-commit.outcome != 'success'
        run: |
          cd llvm
          git bisect start ${{ steps.build-latest-llvm-commit.outputs.sha }} ${{ steps.build-current-llvm-commits.outputs.sha }} -- mlir llvm
          git bisect run cmake --build ../build --config Debug --target check-circt --

      - name: Log broken commit
        if: steps.build-latest-llvm-commit.outcome != 'success'
        run: |
          cd llvm
          git bisect log
          git log

      - name: Fail if incompatible commits exist
        if: steps.build-latest-llvm-commit.outcome != 'success'
        run: exit 1

  # --- end of track-llvm-changes job.
