name: Upload Firrtl Release Artifacts

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Operating System target
        default: linux
        options:
          - linux
          - macos
          - windows
      runTests:
        type: choice
        description: Run CIRCT tests
        default: false
        options:
          - true
          - false
  # Run every day at 0700 UTC which is:
  #   - 0000 PDT / 2300 PST
  #   - 0300 EDT / 0200 EST
  schedule:
    - cron: '0 7 * * *'

jobs:
  publish-sources:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-20.04
    steps:
      # Clone the CIRCT repo and its submodules. Do shallow clone to save clone
      # time.
      - name: Get CIRCT and LLVM
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: "true"

      # Package up sources for distribution, as the default source bundles from GitHub don't include LLVM.
      - name: Create Source Archive
        run: |
          touch circt-full-sources.tar.gz
          tar \
            --exclude-vcs \
            --exclude=circt-full-sources.tar.gz \
            -czf \
            circt-full-sources.tar.gz .
          shasum -a 256 circt-full-sources.tar.gz | cut -d ' ' -f1 > circt-full-sources.tar.gz.sha256

      - name: Upload Source Archive
        uses: AButler/upload-release-assets@v2.0
        with:
          # The * will grab the .sha256 as well
          files: circt-full-sources.tar.gz*
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  # This job sets up the build matrix.
  choose-matrix:
    runs-on: ubuntu-20.04
    steps:
      - name: Add Linux
        id: add-linux
        if: github.event_name != 'workflow_dispatch' || inputs.os == 'linux'
        env:
          os: linux
          runner: ubuntu-20.04
          arch: x64
          tar: tar czf
          archive: tar.gz
          sha256: shasum -a 256
          cont: '\'
          setup:
          cmake_c_compiler: clang-12
          cmake_cxx_compiler: clang++-12
        run: |
          json=$(echo '${{ toJSON(env) }}' | jq -c)
          echo $json
          echo "out=$json" >> $GITHUB_OUTPUT
      - name: Add macOS
        id: add-macos
        if: github.event_name == 'release' || ( github.event_name == 'workflow_dispatch' && inputs.os == 'macos' )
        env:
          os: macos
          runner: macos-11
          arch: x64
          tar: gtar czf
          archive: tar.gz
          sha256: shasum -a 256
          cont: '\'
          setup:
          cmake-args:
          cmake_c_compiler: clang
          cmake_cxx_compiler: clang++
        run: |
          json=$(echo '${{ toJSON(env) }}' | jq -c)
          echo $json
          echo "out=$json" >> $GITHUB_OUTPUT
      - name: Add Windows
        id: add-windows
        if: github.event_name == 'release' || ( github.event_name == 'workflow_dispatch' && inputs.os == 'windows' )
        env:
          os: windows
          runner: windows-2019
          arch: x64
          tar: tar czf
          archive: zip
          sha256: sha256sum
          cont: '`'
          setup: ./utils/find-vs.ps1
          cmake-args:
          cmake_c_compiler: cl
          cmake_cxx_compiler: cl
        run: |
          json=$(echo '${{ toJSON(env) }}' | jq -c)
          echo $json
          echo "out=$json" >> $GITHUB_OUTPUT
      - name: Add Build Options
        id: add-build-options
        run: |
          json='{"mode":"release","assert":"OFF","shared":"OFF","stats":"ON"}'
          if [[ ${{ github.event_name }} == 'schedule' ]] || [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            json=$(echo $json | jq -c '.assert = "ON" | .mode = "relwithdebinfo"')
          fi
          echo "out=$json" >> $GITHUB_OUTPUT
      - name: Build JSON Payloads
        id: build-json-payloads
        run: |
          echo '${{ steps.add-build-options.outputs.out }}' | jq -sc . > options.json
          echo build_configs=`cat options.json` >> $GITHUB_OUTPUT

          echo "Build Config Matrix" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat options.json | jq >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          echo '${{ steps.add-linux.outputs.out }}' '${{ steps.add-macos.outputs.out }}' '${{ steps.add-windows.outputs.out }}' | jq -sc . > runners.json
          echo runners=`cat runners.json` >> $GITHUB_OUTPUT

          echo "Runner/Operating System Matrix:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat runners.json | jq >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          case ${{ github.event_name }} in
            workflow_dispatch)
              ENV='[{"runTests":${{ inputs.runTests }}}]'
            ;;
            schedule)
              ENV='[{"runTests":false}]'
            ;;
            *)
              ENV='[{"runTests":true}]'
            ;;
          esac
          echo environment=$ENV >> $GITHUB_OUTPUT

          echo "Environment Configuration:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo $ENV | jq >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
    outputs:
      build_configs: ${{ steps.build-json-payloads.outputs.build_configs }}
      runners: ${{ steps.build-json-payloads.outputs.runners }}
      environment: ${{ steps.build-json-payloads.outputs.environment }}

  publish:
    needs:
      - choose-matrix
    strategy:
      matrix:
        build_config: ${{ fromJSON(needs.choose-matrix.outputs.build_configs) }}
        runner: ${{ fromJSON(needs.choose-matrix.outputs.runners) }}
        env: ${{ fromJSON(needs.choose-matrix.outputs.environment) }}
    uses: ./.github/workflows/unifiedBuildTestAndInstall.yml
    with:
      runner: ${{ matrix.runner.runner }}
      cmake_build_type: ${{ matrix.build_config.mode }}
      build_shared_libs: ${{ matrix.build_config.shared }}
      llvm_enable_assertions: ${{ matrix.build_config.assert }}
      llvm_force_enable_stats: ${{ matrix.build_config.stats }}
      runTests: ${{ matrix.env.runTests }}
      install: install-firtool
      cmake_c_compiler: ${{ matrix.runner.cmake_c_compiler }}
      cmake_cxx_compiler: ${{ matrix.runner.cmake_cxx_compiler }}
